/**
 * **Où poser un pays sur le globe** (24/09) — **tous les pays du monde** (236 territoires),
 * générés une fois hors du dépôt depuis Natural Earth 1:50 m (\`world-atlas\`, domaine
 * public) : le centre de leur **plus grand territoire** (la France n'est pas tirée vers la
 * Guyane), leur nom français (\`Intl.DisplayNames\`), leur nom anglais et leur code ISO.
 *
 * Le référentiel ne porte que le **nom** d'un pays. Il est reconnu en français, en anglais
 * ou par son code, sans casse ni accent, avec les variantes d'usage (RDC, Centrafrique…).
 * Un nom inconnu n'est pas placé : la page le dit, elle n'invente pas une position.
 */
type Pays = readonly [code: string, fr: string, en: string, lat: number, lng: number];

const PAYS: readonly Pays[] = [
    ['AF', 'Afghanistan', 'Afghanistan', 33.8, 65.9],
    ['ZA', 'Afrique du Sud', 'South Africa', -29, 25.2],
    ['AL', 'Albanie', 'Albania', 41.1, 20.1],
    ['DZ', 'Algérie', 'Algeria', 28.1, 2.6],
    ['DE', 'Allemagne', 'Germany', 51, 10.4],
    ['AD', 'Andorre', 'Andorra', 42.5, 1.6],
    ['AO', 'Angola', 'Angola', -12.3, 17.6],
    ['AI', 'Anguilla', 'Anguilla', 18.2, -63.1],
    ['AQ', 'Antarctique', 'Antarctica', -84.7, 83],
    ['AG', 'Antigua-et-Barbuda', 'Antigua and Barb.', 17.1, -61.8],
    ['SA', 'Arabie saoudite', 'Saudi Arabia', 24.1, 44.7],
    ['AR', 'Argentine', 'Argentina', -34.5, -64.7],
    ['AM', 'Arménie', 'Armenia', 40.3, 44.9],
    ['AW', 'Aruba', 'Aruba', 12.5, -70],
    ['AU', 'Australie', 'Australia', -25.6, 134.2],
    ['AT', 'Autriche', 'Austria', 47.6, 14.1],
    ['AZ', 'Azerbaïdjan', 'Azerbaijan', 40.3, 47.7],
    ['BS', 'Bahamas', 'Bahamas', 24.7, -78],
    ['BH', 'Bahreïn', 'Bahrain', 26, 50.5],
    ['BD', 'Bangladesh', 'Bangladesh', 23.9, 90.2],
    ['BB', 'Barbade', 'Barbados', 13.2, -59.6],
    ['BE', 'Belgique', 'Belgium', 50.6, 4.6],
    ['BZ', 'Belize', 'Belize', 17.2, -88.7],
    ['BJ', 'Bénin', 'Benin', 9.6, 2.3],
    ['BM', 'Bermudes', 'Bermuda', 32.3, -64.8],
    ['BT', 'Bhoutan', 'Bhutan', 27.4, 90.4],
    ['BY', 'Biélorussie', 'Belarus', 53.5, 28],
    ['BO', 'Bolivie', 'Bolivia', -16.7, -64.7],
    ['BA', 'Bosnie-Herzégovine', 'Bosnia and Herz.', 44.2, 17.8],
    ['BW', 'Botswana', 'Botswana', -22.2, 23.8],
    ['BR', 'Brésil', 'Brazil', -10.7, -53.2],
    ['BN', 'Brunei', 'Brunei', 4.5, 114.6],
    ['BG', 'Bulgarie', 'Bulgaria', 42.8, 25.2],
    ['BF', 'Burkina Faso', 'Burkina Faso', 12.3, -1.8],
    ['BI', 'Burundi', 'Burundi', -3.4, 29.9],
    ['KH', 'Cambodge', 'Cambodia', 12.7, 104.9],
    ['CM', 'Cameroun', 'Cameroon', 5.7, 12.7],
    ['CA', 'Canada', 'Canada', 58.6, -99],
    ['CV', 'Cap-Vert', 'Cabo Verde', 15.1, -23.6],
    ['CL', 'Chili', 'Chile', -34.4, -70.9],
    ['CN', 'Chine', 'China', 36.8, 103.3],
    ['CY', 'Chypre', 'Cyprus', 34.9, 33],
    ['CO', 'Colombie', 'Colombia', 3.9, -73.1],
    ['KM', 'Comores', 'Comoros', -11.7, 43.3],
    ['CG', 'Congo-Brazzaville', 'Congo', -0.8, 15.2],
    ['CD', 'Congo-Kinshasa', 'Dem. Rep. Congo', -2.9, 23.6],
    ['KP', 'Corée du Nord', 'North Korea', 40.1, 127.2],
    ['KR', 'Corée du Sud', 'South Korea', 36.5, 127.9],
    ['CR', 'Costa Rica', 'Costa Rica', 10, -84.2],
    ['CI', 'Côte d’Ivoire', "Côte d'Ivoire", 7.6, -5.6],
    ['HR', 'Croatie', 'Croatia', 45.2, 16.4],
    ['CU', 'Cuba', 'Cuba', 21.6, -78.9],
    ['CW', 'Curaçao', 'Curaçao', 12.2, -69],
    ['DK', 'Danemark', 'Denmark', 56.2, 9.3],
    ['DJ', 'Djibouti', 'Djibouti', 11.7, 42.6],
    ['DM', 'Dominique', 'Dominica', 15.4, -61.4],
    ['EG', 'Égypte', 'Egypt', 26.5, 29.9],
    ['AE', 'Émirats arabes unis', 'United Arab Emirates', 23.9, 54.3],
    ['EC', 'Équateur', 'Ecuador', -1.4, -78.4],
    ['ER', 'Érythrée', 'Eritrea', 15.4, 38.8],
    ['ES', 'Espagne', 'Spain', 40.4, -3.6],
    ['EE', 'Estonie', 'Estonia', 58.7, 25.8],
    ['SZ', 'Eswatini', 'eSwatini', -26.6, 31.5],
    ['VA', 'État de la Cité du Vatican', 'Vatican', 41.9, 12.4],
    ['US', 'États-Unis', 'United States of America', 39.9, -98.8],
    ['ET', 'Éthiopie', 'Ethiopia', 8.6, 39.6],
    ['FJ', 'Fidji', 'Fiji', -17.8, 178],
    ['FI', 'Finlande', 'Finland', 64.3, 26.2],
    ['FR', 'France', 'France', 46.6, 2.5],
    ['GA', 'Gabon', 'Gabon', -0.6, 11.8],
    ['GM', 'Gambie', 'Gambia', 13.5, -15.4],
    ['GE', 'Géorgie', 'Georgia', 42.2, 43.5],
    ['GS', 'Géorgie du Sud-et-les Îles Sandwich du Sud', 'S. Geo. and the Is.', -54.4, -36.7],
    ['GH', 'Ghana', 'Ghana', 7.9, -1.2],
    ['GR', 'Grèce', 'Greece', 39.5, 22.6],
    ['GD', 'Grenade', 'Grenada', 12.1, -61.7],
    ['GL', 'Groenland', 'Greenland', 73.1, -41.8],
    ['GU', 'Guam', 'Guam', 13.4, 144.8],
    ['GT', 'Guatemala', 'Guatemala', 15.7, -90.4],
    ['GG', 'Guernesey', 'Guernsey', 49.5, -2.6],
    ['GN', 'Guinée', 'Guinea', 10.4, -10.9],
    ['GQ', 'Guinée équatoriale', 'Eq. Guinea', 1.6, 10.5],
    ['GW', 'Guinée-Bissau', 'Guinea-Bissau', 12.1, -14.9],
    ['GY', 'Guyana', 'Guyana', 4.8, -59],
    ['HT', 'Haïti', 'Haiti', 18.9, -72.7],
    ['HN', 'Honduras', 'Honduras', 14.8, -86.6],
    ['HU', 'Hongrie', 'Hungary', 47.2, 19.4],
    ['IM', 'Île de Man', 'Isle of Man', 54.2, -4.5],
    ['NF', 'Île Norfolk', 'Norfolk Island', -29.1, 167.9],
    ['AX', 'Îles Åland', 'Åland', 60.2, 19.9],
    ['KY', 'Îles Caïmans', 'Cayman Is.', 19.3, -81.3],
    ['CK', 'Îles Cook', 'Cook Is.', -21.2, -159.8],
    ['FO', 'Îles Féroé', 'Faeroe Is.', 62.2, -6.9],
    ['HM', 'Îles Heard-et-MacDonald', 'Heard I. and McDonald Is.', -53.1, 73.5],
    ['FK', 'Îles Malouines', 'Falkland Is.', -51.7, -58.8],
    ['MP', 'Îles Mariannes du Nord', 'N. Mariana Is.', 15.2, 145.7],
    ['MH', 'Îles Marshall', 'Marshall Is.', 7.1, 171.2],
    ['PN', 'Îles Pitcairn', 'Pitcairn Is.', -24.4, -128.3],
    ['SB', 'Îles Salomon', 'Solomon Is.', -9.6, 160.2],
    ['TC', 'Îles Turques-et-Caïques', 'Turks and Caicos Is.', 21.8, -71.7],
    ['VG', 'Îles Vierges britanniques', 'British Virgin Is.', 18.4, -64.6],
    ['VI', 'Îles Vierges des États-Unis', 'U.S. Virgin Is.', 17.7, -64.8],
    ['IN', 'Inde', 'India', 22.8, 79.5],
    ['ID', 'Indonésie', 'Indonesia', -0.2, 114],
    ['IQ', 'Irak', 'Iraq', 33, 43.8],
    ['IR', 'Iran', 'Iran', 32.5, 54.4],
    ['IE', 'Irlande', 'Ireland', 53.2, -8.1],
    ['IS', 'Islande', 'Iceland', 65, -18.6],
    ['IL', 'Israël', 'Israel', 31.5, 35],
    ['IT', 'Italie', 'Italy', 43.5, 12.3],
    ['JM', 'Jamaïque', 'Jamaica', 18.2, -77.3],
    ['JP', 'Japon', 'Japan', 36.6, 137.9],
    ['JE', 'Jersey', 'Jersey', 49.2, -2.1],
    ['JO', 'Jordanie', 'Jordan', 31.2, 36.8],
    ['KZ', 'Kazakhstan', 'Kazakhstan', 48.4, 67.2],
    ['KE', 'Kenya', 'Kenya', 0.6, 37.8],
    ['KG', 'Kirghizstan', 'Kyrgyzstan', 41.5, 74.5],
    ['KI', 'Kiribati', 'Kiribati', 1.9, -157.4],
    ['XK', 'Kosovo', 'Kosovo', 42.6, 20.9],
    ['KW', 'Koweït', 'Kuwait', 29.3, 47.6],
    ['LA', 'Laos', 'Laos', 18.5, 103.8],
    ['LS', 'Lesotho', 'Lesotho', -29.6, 28.2],
    ['LV', 'Lettonie', 'Latvia', 56.9, 24.9],
    ['LB', 'Liban', 'Lebanon', 33.9, 35.9],
    ['LR', 'Liberia', 'Liberia', 6.5, -9.3],
    ['LY', 'Libye', 'Libya', 27, 18.1],
    ['LI', 'Liechtenstein', 'Liechtenstein', 47.1, 9.5],
    ['LT', 'Lituanie', 'Lithuania', 55.3, 23.9],
    ['LU', 'Luxembourg', 'Luxembourg', 49.8, 6.1],
    ['MK', 'Macédoine du Nord', 'Macedonia', 41.6, 21.7],
    ['MG', 'Madagascar', 'Madagascar', -19.3, 46.7],
    ['MY', 'Malaisie', 'Malaysia', 3.6, 114.7],
    ['MW', 'Malawi', 'Malawi', -13.2, 34.3],
    ['MV', 'Maldives', 'Maldives', 4.2, 73.5],
    ['ML', 'Mali', 'Mali', 17.3, -3.6],
    ['MT', 'Malte', 'Malta', 35.9, 14.4],
    ['MA', 'Maroc', 'Morocco', 29.8, -8.7],
    ['MU', 'Maurice', 'Mauritius', -20.3, 57.6],
    ['MR', 'Mauritanie', 'Mauritania', 20.2, -10.4],
    ['MX', 'Mexique', 'Mexico', 23.9, -102.2],
    ['FM', 'Micronésie', 'Micronesia', 6.9, 158.2],
    ['MD', 'Moldavie', 'Moldova', 47.2, 28.5],
    ['MC', 'Monaco', 'Monaco', 43.8, 7.4],
    ['MN', 'Mongolie', 'Mongolia', 47, 103.1],
    ['ME', 'Monténégro', 'Montenegro', 42.8, 19.2],
    ['MS', 'Montserrat', 'Montserrat', 16.7, -62.2],
    ['MZ', 'Mozambique', 'Mozambique', -17.2, 35.6],
    ['MM', 'Myanmar (Birmanie)', 'Myanmar', 21.1, 96.5],
    ['NA', 'Namibie', 'Namibia', -22.1, 17.2],
    ['NR', 'Nauru', 'Nauru', -0.5, 166.9],
    ['NP', 'Népal', 'Nepal', 28.3, 83.9],
    ['NI', 'Nicaragua', 'Nicaragua', 12.8, -85],
    ['NE', 'Niger', 'Niger', 17.4, 9.3],
    ['NG', 'Nigeria', 'Nigeria', 9.6, 8.1],
    ['NU', 'Niue', 'Niue', -19, -169.9],
    ['NO', 'Norvège', 'Norway', 63.8, 12.2],
    ['NC', 'Nouvelle-Calédonie', 'New Caledonia', -21.3, 165.5],
    ['NZ', 'Nouvelle-Zélande', 'New Zealand', -43.9, 170.6],
    ['OM', 'Oman', 'Oman', 20.6, 56.1],
    ['UG', 'Ouganda', 'Uganda', 1.3, 32.4],
    ['UZ', 'Ouzbékistan', 'Uzbekistan', 41.8, 63.3],
    ['PK', 'Pakistan', 'Pakistan', 29.9, 69.2],
    ['PW', 'Palaos', 'Palau', 7.5, 134.6],
    ['PA', 'Panama', 'Panama', 8.5, -80.1],
    ['PG', 'Papouasie-Nouvelle-Guinée', 'Papua New Guinea', -6.6, 144.2],
    ['PY', 'Paraguay', 'Paraguay', -23.2, -58.4],
    ['NL', 'Pays-Bas', 'Netherlands', 52.3, 5.6],
    ['PE', 'Pérou', 'Peru', -9.1, -74.4],
    ['PH', 'Philippines', 'Philippines', 15.9, 121.4],
    ['PL', 'Pologne', 'Poland', 52.1, 19.4],
    ['PF', 'Polynésie française', 'Fr. Polynesia', -17.7, -149.4],
    ['PR', 'Porto Rico', 'Puerto Rico', 18.2, -66.5],
    ['PT', 'Portugal', 'Portugal', 39.7, -8],
    ['QA', 'Qatar', 'Qatar', 25.3, 51.2],
    ['HK', 'R.A.S. chinoise de Hong Kong', 'Hong Kong', 22.4, 114.1],
    ['MO', 'R.A.S. chinoise de Macao', 'Macao', 22.2, 113.5],
    ['CF', 'République centrafricaine', 'Central African Rep.', 6.6, 20.5],
    ['DO', 'République dominicaine', 'Dominican Rep.', 18.9, -70.5],
    ['RO', 'Roumanie', 'Romania', 45.8, 25],
    ['GB', 'Royaume-Uni', 'United Kingdom', 53.8, -2.4],
    ['RU', 'Russie', 'Russia', 65.9, 95.5],
    ['RW', 'Rwanda', 'Rwanda', -2, 29.9],
    ['EH', 'Sahara occidental', 'W. Sahara', 24.2, -12.3],
    ['BL', 'Saint-Barthélemy', 'St-Barthélemy', 17.9, -62.8],
    ['KN', 'Saint-Christophe-et-Niévès', 'St. Kitts and Nevis', 17.3, -62.7],
    ['SM', 'Saint-Marin', 'San Marino', 43.9, 12.5],
    ['MF', 'Saint-Martin', 'St-Martin', 18.1, -63.1],
    ['SX', 'Saint-Martin (partie néerlandaise)', 'Sint Maarten', 18.1, -63.1],
    ['PM', 'Saint-Pierre-et-Miquelon', 'St. Pierre and Miquelon', 46.9, -56.3],
    ['VC', 'Saint-Vincent-et-les Grenadines', 'St. Vin. and Gren.', 13.3, -61.2],
    ['SH', 'Sainte-Hélène', 'Saint Helena', -16, -5.7],
    ['LC', 'Sainte-Lucie', 'Saint Lucia', 13.9, -61],
    ['SV', 'Salvador', 'El Salvador', 13.7, -88.9],
    ['WS', 'Samoa', 'Samoa', -13.6, -172.4],
    ['AS', 'Samoa américaines', 'American Samoa', -14.3, -170.7],
    ['ST', 'Sao Tomé-et-Principe', 'São Tomé and Principe', 0.2, 6.6],
    ['SN', 'Sénégal', 'Senegal', 14.4, -14.5],
    ['RS', 'Serbie', 'Serbia', 44.2, 20.8],
    ['SC', 'Seychelles', 'Seychelles', -4.7, 55.5],
    ['SL', 'Sierra Leone', 'Sierra Leone', 8.6, -11.8],
    ['SG', 'Singapour', 'Singapore', 1.4, 103.8],
    ['SK', 'Slovaquie', 'Slovakia', 48.7, 19.5],
    ['SI', 'Slovénie', 'Slovenia', 46.1, 14.8],
    ['SO', 'Somalie', 'Somalia', 4.7, 45.7],
    ['SD', 'Soudan', 'Sudan', 16, 29.9],
    ['SS', 'Soudan du Sud', 'S. Sudan', 7.3, 30.3],
    ['LK', 'Sri Lanka', 'Sri Lanka', 7.6, 80.7],
    ['SE', 'Suède', 'Sweden', 62.4, 16.2],
    ['CH', 'Suisse', 'Switzerland', 46.8, 8.2],
    ['SR', 'Suriname', 'Suriname', 4.1, -55.9],
    ['SY', 'Syrie', 'Syria', 35, 38.5],
    ['TJ', 'Tadjikistan', 'Tajikistan', 38.5, 71],
    ['TW', 'Taïwan', 'Taiwan', 23.7, 121],
    ['TZ', 'Tanzanie', 'Tanzania', -6.3, 34.8],
    ['TD', 'Tchad', 'Chad', 15.3, 18.6],
    ['CZ', 'Tchéquie', 'Czechia', 49.7, 15.3],
    ['TF', 'Terres australes françaises', 'Fr. S. Antarctic Lands', -49.3, 69.5],
    ['IO', 'Territoire britannique de l’océan Indien', 'Br. Indian Ocean Ter.', -7.3, 72.4],
    ['PS', 'Territoires palestiniens', 'Palestine', 31.9, 35.2],
    ['TH', 'Thaïlande', 'Thailand', 15.1, 101],
    ['TL', 'Timor oriental', 'Timor-Leste', -8.8, 125.9],
    ['TG', 'Togo', 'Togo', 8.5, 1],
    ['TO', 'Tonga', 'Tonga', -21.2, -175.2],
    ['TT', 'Trinité-et-Tobago', 'Trinidad and Tobago', 10.4, -61.3],
    ['TN', 'Tunisie', 'Tunisia', 34.1, 9.6],
    ['TM', 'Turkménistan', 'Turkmenistan', 39.1, 59.4],
    ['TR', 'Turquie', 'Turkey', 39.1, 35.4],
    ['UA', 'Ukraine', 'Ukraine', 49.2, 31.3],
    ['UY', 'Uruguay', 'Uruguay', -32.8, -56],
    ['VU', 'Vanuatu', 'Vanuatu', -15.2, 166.8],
    ['VE', 'Venezuela', 'Venezuela', 7.1, -66.2],
    ['VN', 'Viêt Nam', 'Vietnam', 16.5, 106.3],
    ['WF', 'Wallis-et-Futuna', 'Wallis and Futuna Is.', -14.3, -178.1],
    ['YE', 'Yémen', 'Yemen', 15.9, 47.5],
    ['ZM', 'Zambie', 'Zambia', -13.5, 27.8],
    ['ZW', 'Zimbabwe', 'Zimbabwe', -19, 29.9],
];

/** Les noms d'usage qui ne sont pas ceux d'\`Intl.DisplayNames\`. */
const ALIAS: Record<string, string> = {
    rdc: 'CD',
    'republique democratique du congo': 'CD',
    'congo kinshasa': 'CD',
    congo: 'CG',
    'republique du congo': 'CG',
    'congo brazzaville': 'CG',
    centrafrique: 'CF',
    'republique centrafricaine': 'CF',
    usa: 'US',
    'etats unis d amerique': 'US',
    'grande bretagne': 'GB',
    angleterre: 'GB',
    'pays bas': 'NL',
    hollande: 'NL',
    'coree du sud': 'KR',
    'coree du nord': 'KP',
    birmanie: 'MM',
    'cote divoire': 'CI',
    'ivory coast': 'CI',
    'cap vert': 'CV',
    eswatini: 'SZ',
    swaziland: 'SZ',
    tchequie: 'CZ',
    'republique tcheque': 'CZ',
};

/* Tolérante (24/09) : un nom venu de la base peut ne pas être du texte ; il ne doit pas
   faire tomber la page, seulement ne pas être placé. */
const clef = (nom: unknown): string =>
    String(nom ?? '')
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .toLowerCase()
        .replace(/[^a-z]+/g, ' ')
        .trim();

const INDEX = (() => {
    const index = new Map<string, Pays>();
    const parCode = new Map<string, Pays>();
    for (const pays of PAYS) {
        parCode.set(pays[0], pays);
        index.set(clef(pays[1]), pays);
        index.set(clef(pays[2]), pays);
        index.set(pays[0].toLowerCase(), pays);
    }
    for (const [alias, code] of Object.entries(ALIAS)) {
        const pays = parCode.get(code);
        if (pays) index.set(alias, pays);
    }
    return index;
})();

/** La position d'un pays sur le globe, ou \`null\` si son nom n'est pas reconnu. */
export const positionDuPays = (nom: unknown): [number, number] | null => {
    const pays = INDEX.get(clef(nom));
    return pays ? [pays[3], pays[4]] : null;
};

/** Le code ISO d'un pays reconnu — l'étiquette de sa pastille. */
export const codeDuPays = (nom: unknown): string | null => INDEX.get(clef(nom))?.[0] ?? null;
